### ISSUE TITLE
다 만들면 알려줘 읽어볼께

### ISSUE THREAD

**Issue by Sinawe4** [Goolgae/fastcampus#1]
프론트 공부를 위해 강의를 볼까 했는데 강의 보고 이해가 가지않는 부분은 너의 요약으로 공부해볼께

**Comment by Goolgae** [comment]
'게' 새끼야

**Comment by Sinawe4** [comment]
> '게' 새끼야

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
